### ISSUE TITLE
where is the web/dist folder? 

### ISSUE THREAD

**Issue by yuezhilanyi** [casdoor/casdoor-fastapi-js-sdk-example#3]
i run app ending with error info below:

> (services) PS D:\casdoor-fastapi-js-sdk-example> python .\app.py   
Traceback (most recent call last):
  File "D:\casdoor-fastapi-js-sdk-example\app.py", line 34, in <module>
    app.mount("/web", StaticFiles(directory="./web/dist", html=True), name="web")
  File "D:\miniconda3\envs\services\lib\site-packages\starlette\staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory './web/dist' does not exist

could someone tell me where can i get the missing folder or files?

**Comment by hsluoyz** [comment]
@yuezhilanyi compile the frontend first:

```
cd web
yarn install
yarn build
```

**Comment by yuezhilanyi** [comment]
> @yuezhilanyi compile the frontend first:
> 
> ```
> cd web
> yarn install
> yarn build
> ```

thank you, it worked.
The README is missing this command (yarn build). Can we add it later to make sure other people can run this demo smoothly? Because some people(just like me) are backend developers and not familiar with frontend.
