### ISSUE TITLE
[bug] make the example work

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-fastapi-js-sdk-example#4]
This FastAPI example is originated from the Flask example: https://github.com/casdoor/casdoor-fastapi-js-sdk-example/commit/4d23d7a7563b9b8899886e9255f33936b872754c

But it seems that it doesn't work yet like the Flask one in the demo video (the video is still the Flask one): https://github.com/casdoor/casdoor-fastapi-js-sdk-example?tab=readme-ov-file#demo-videos

Need to fix existing bugs to make it really work

**Comment by MovisLi** [comment]
Because in `/api/login.py`, `user = sdk.parse_jwt_token(token)` should be `user = sdk.parse_jwt_token(token["access_token"])`

**Comment by hsluoyz** [comment]
@MovisLi fixed by: https://github.com/casdoor/casdoor-fastapi-js-sdk-example/commit/56913939aa972d16640346b456cea2e76cffface
